routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontPageController@index')->name('welcome');

Route::get('/admin/instructivo', function () {
    return view('admin.instructivo');
});

Route::get('/categoria/{id}', 'FrontPageController@showCategoria')->name('categoria');

Auth::routes();

//Route::get('/admin', 'PrincipalController@index');
Route::get('/admin', ['as' => 'admin', 'uses' => 'PrincipalController@index']);
Route::get('/admin/productos/get_data_productos', ['as' => 'get_data_productos', 'uses' => 'ProductosController@get_data']);
Route::get('/admin/productos/get_link_pdf', ['as' => 'get_link_pdf', 'uses' => 'ProductosController@download_pdf']);
Route::get('/admin/categorias/get_data_categorias', ['as' => 'get_data_categorias', 'uses' => 'CategoriasController@get_data']);
Route::get('/admin/marcas/get_data_marcas', ['as' => 'get_data_marcas', 'uses' =>'MarcasController@get_data']);
//CATEGORIAS
Route::get('/admin/productos/get_tipos/{id}', 'CategoriasController@getTipos')->name('get_tipos_selectbox');
Route::post('/admin/categorias/set_data_categoria', 'CategoriasController@store')->name('set_data_categoria');
Route::patch('/admin/categorias/upd_data_categoria', 'CategoriasController@update')->name('upd_data_categoria');
Route::delete('/admin/categorias/del_data_categoria', 'CategoriasController@destroy')->name('del_data_categoria');
//MARCAS
Route::get('/admin/productos/get_modelos/{id}', 'MarcasController@getModelos')->name('get_modelos_selectbox');
Route::post('/admin/marcas/set_data_marca', 'MarcasController@store')->name('set_data_marca');
Route::patch('/admin/marcas/upd_data_marca', 'MarcasController@update')->name('upd_data_marca');
Route::delete('/admin/marcas/del_data_marca', 'MarcasController@destroy')->name('del_data_marca');
//PRODUCTOS
Route::resource('/admin/productos', 'ProductosController');
Route::post('/admin/productos/set_data_producto', 'ProductosController@store')->name('set_data_producto');
Route::delete('/admin/productos/del_data_producto', 'ProductosController@destroy')->name('del_data_producto');
/* Route::resource('/admin/categorias', 'CategoriasController'); */
/* Route::resource('/admin/marcas', 'MarcasController'); */

resources/views/admin/addproductos.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('css/component.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="sidebar-overlay" id="sidebar-overlay"></div>
    <div class="title-block">
        <h3 class="title"> Agregue un Nuevo Producto <span class="sparkline bar" data-type="bar"></span> </h3>
    </div>
    <p id="output-success-producto"></p>
    <form id="add-producto" name="producto" method="POST" enctype="multipart/form-data" action="{{ route('productos.store') }}">
        {{ csrf_field() }}
        <div class="card card-block">
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Categoría:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="categoria" id="categoria" title="Selección de Categoría">
                        <option value="">--Seleccione Categoría--</option>
                        @foreach ($categorias as $categoria)
                            <option value="{{ $categoria->id }}"> {{ $categoria->categoria }}</option>
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Tipo:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="tipo" id="tipo" title="Selección de Tipo" disabled>
                        <option>--Seleccione Tipo--</option>
                    </select>
                </div>
                <div class="col-md-2"><span id="loader-tipos" class="d-none"><i class="fa fa-spinner fa-2x fa-spin"></i></span></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Marca:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="marca" id="marca" title="Selección de Marca">
                        <option value="">--Seleccione Marca--</option>
                        @foreach ($marcas as $marca)
                            <option value="{{ $marca->id }}"> {{ $marca->marca }}</option>   
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Modelo:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="modelo" id="modelo" title="Selección de Modelo" disabled>
                        <option>--Seleccione Modelo--</option>
                    </select>
                </div>
                <div class="col-md-2"><span id="loader-modelos" class="d-none"><i class="fa fa-spinner fa-2x fa-spin"></i></span></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Nombre:
                </label>
                <div class="col-sm-3"> <input type="text" class="form-control boxed" name="nombre" id="nombre" value="{{ old('nombre') }}" placeholder="Ingrese Nombre Producto"> </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Código:
                </label>
                <div class="col-sm-3"> <input type="text" class="form-control boxed" name="codigo" id="codigo" value="{{ old('codigo') }}" placeholder="Ingrese Código Producto"> </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Ficha Técnica:
                </label>
                <div class="col-sm-10">
                    <div class="box js" title="Cargar PDF">
                        <input type="file" name="pdf" id="file-2" class="inputfile inputfile-6" accept="application/pdf" onchange="readURL(this, 'pdf');"/>
                        <label for="file-2"><span></span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Seleccione PDF&hellip;</strong></label>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Descripción:
                </label>
            </div>
            <div class="form-group row">
                <div class="col-sm-12">
                    <textarea id="descripcion" name="descripcion">{{ old('descripcion') }}</textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Imágen:
                </label>
                <div class="col-sm-10">
                    <div class="box js" title="Cargar Imágen">
                        <input type="file" name="imagen" id="file-1" class="inputfile inputfile-6" accept="image/*" onchange="readURL(this, 'image');"/>
                        <label for="file-1"><span></span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Seleccione Imágen&hellip;</strong></label>
                        <div class="col-sm-12">
                            <img id="preview-image" class="sizing transparent" src="#" alt="" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12"> <button type="submit" class="btn btn-primary" id="btn_guardar" title="Guardar Producto">
                    Guardar
                    </button> 
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script>
        var error = {
                'error': '{{$errors->any()}}',
                'categoria': '{{old('categoria')}}',
                'tipo': '{{old('tipo')}}',
                'marca': '{{old('marca')}}',
                'modelo': '{{old('modelo')}}',
            };
    </script>
    <script src="{{asset ('vendor/tinymce/tinymce.min.js')}}"></script>
    <script src="{{asset ('js/Productos/jquery.custom-file-input.js')}}"></script>
    <script src="{{asset ('js/Productos/textEditor-cfg.js')}}"></script>
    <script src="{{asset ('js/Productos/selectBoxLoad.js')}}"></script>
@endsection

resources/views/admin/editproductos.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('css/component.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="sidebar-overlay" id="sidebar-overlay"></div>
    <div class="title-block">
        <h3 class="title"> Editar Producto {{$producto->codigo}}<span class="sparkline bar" data-type="bar"></span> </h3>
    </div>
    <form id="edit-producto" name="producto" enctype="multipart/form-data" action="{{route('productos.update', 'editar')}}" method="post">
        {{method_field('patch')}}
        {{csrf_field()}}
        <input type="hidden" name="producto_id" id="producto_id" value="{{$producto->id}}">
        <div class="card card-block">
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Categoría:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="categoria" id="categoria" title="Selección de Categoría">
                        <option value="">--Seleccione Categoría--</option>
                        @foreach ($categorias as $categoria)
                            <option value="{{ $categoria->id }}"> {{ $categoria->categoria }}</option>
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Tipo:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="tipo" id="tipo" title="Selección de Tipo">
                        <option>--Seleccione Tipo--</option>
                    </select>
                </div>
                <div class="col-md-2"><span id="loader-tipos" class="d-none"><i class="fa fa-spinner fa-2x fa-spin"></i></span></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Marca:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="marca" id="marca" title="Selección de Marca">
                        <option value="">--Seleccione Marca--</option>
                        @foreach ($marcas as $marca)
                            <option value="{{ $marca->id }}"> {{ $marca->marca }}</option>   
                        @endforeach
                    </select>
                </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Modelo:
                </label>
                <div class="col-sm-3">
                    <select class="c-select form-control boxed" name="modelo" id="modelo" title="Selección de Modelo">
                        <option>--Seleccione Modelo--</option>
                    </select>
                </div>
                <div class="col-md-2"><span id="loader-modelos" class="d-none"><i class="fa fa-spinner fa-2x fa-spin"></i></span></div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Nombre:
                </label>
                <div class="col-sm-3"> <input type="text" class="form-control boxed" name="nombre" id="nombre" value="{{ $producto->nombre }}" placeholder="Ingrese Nombre Producto"> </div>
                <label class="col-sm-1 form-control-label text-xs-right">
                    Código:
                </label>
                <div class="col-sm-3"> <input type="text" class="form-control boxed" name="codigo" id="codigo" value="{{ $producto->codigo }}" placeholder="Ingrese Código Producto"> </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Ficha Técnica:
                </label>
                <div class="col-sm-7">
                    <div class="box js" title="Cargar PDF">
                        <input type="file" name="pdf" id="file-2" class="inputfile inputfile-6" accept="application/pdf" onchange="readURL(this, 'pdf');"/>
                        <label for="file-2"><span>{{$pdfName}}</span>
                            <strong>
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17">
                                    <path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/>
                                </svg>
                                Seleccione PDF&hellip;
                            </strong>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-block">
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Descripción:
                </label>
            </div>
            <div class="form-group row">
                <div class="col-sm-12">
                    <textarea id="descripcion" name="descripcion">{{ $producto->descripcion }}</textarea>
                </div>
            </div>
        </div>
        <div class="card card-block">
            <div class="form-group row">
                <label class="col-sm-1 form-control-label text-xs-right">
                    Imágen:
                </label>
                <div class="col-sm-11">
                    <div class="box js" title="Cargar Imágen">
                        <input type="file" name="imagen" id="file-1" class="inputfile inputfile-6" accept="image/*" onchange="readURL(this, 'image');"/>
                    <label for="file-1"><span>{{$imageName}}</span> <strong><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> Seleccione Imágen&hellip;</strong></label>
                        <div class="col-lg-8">
                            <div class="card center-block">
                                <img id="preview-image" class="sizing" src="#" alt="" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12"> <button type="submit" class="btn btn-primary" id="btn_guardar" title="Guardar Producto">
                    Guardar
                    </button> 
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script>
        var error = {
                'error': '{{$errors->any()}}',
                'categoria': '{{old('categoria')}}',
                'tipo': '{{old('tipo')}}',
                'marca': '{{old('marca')}}',
                'modelo': '{{old('modelo')}}',
            };

        var valorSeleccionado = {
                'categoria': '{{$producto->categoria_id}}',
                'tipo': '{{$producto->tipo_id}}',
                'marca': '{{$producto->marca_id}}',
                'modelo': '{{$producto->modelo_id}}',
                'image': '{{asset("$image")}}',
            };
    </script>
    <script src="{{asset ('vendor/tinymce/tinymce.min.js')}}"></script>
    <script src="{{asset ('js/Productos/jquery.custom-file-input.js')}}"></script>
    <script src="{{asset ('js/Productos/textEditor-cfg.js')}}"></script>
    <script src="{{asset ('js/Productos/selectBoxLoad.js')}}"></script>
@endsection

resources/views/admin/instructivo.blade.php
@extends('layouts.admin')

@section('content')
    <article class="content dashboard-page">
        <section class="section">
            <div class="row">
                <div class="col col-md-4">
                    <div class="card">
                        <h1>Instrucciones</h1>
                    </div>
                </div>                
            </div>
        </section>
    </article>
@endsection

resources/views/admin/principal.blade.php
@extends('layouts.admin')

@section('styles')
<link rel="stylesheet" type="text/css" href="{{asset('plugins/DataTables/datatables.css')}}"/>
    <link href="{{ asset('css/component.css') }}" rel="stylesheet">
@endsection

@section('content')
    <section id="productos">
        <div class="title-block">
            <h1 class="title"> Productos </h1>
            <p class="title-description"> Lista de productos en el sistema </p>
        </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <p id="output-success-producto"></p>
                            <table class="table table-bordered table-hover" id="productos-table" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Imágen</th>
                                        <th>Código</th>
                                        <th>Nombre</th>
                                        <th>Categoría</th>
                                        <th>Tipo</th>
                                        <th>Marca</th>
                                        <th>Modelo</th>
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    </section>
    <section id="categorias">
        <div class="row">
            <div class="col-md-12 center-block">
                <div class="title-block title-margin">
                    <div class="row justify-content-between">
                        <div class="col-md-6">
                            <h1 class="title">Lista de Categorías</h1>
                            <p class="title-description">y tipos respectivos</p>
                        </div>
                        <div class="col-md-6">
                            <button type="button" id="open_form_categorias" class="btn btn-success pull-right" data-toggle="modal" data-target="#add-categoria-modal" title="Agregar Nueva Categoría">
                                <i class="fa fa-plus"></i>
                                Agregar Nueva Categoría
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 center-block">
                <div class="card">
                    <div class="card-block">
                        <p id="output-success-categoria"></p>
                        <table class="table table-bordered table-hover" id="categorias-table" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Imágen</th>
                                    <th>Categoría</th>
                                    <th>Tipos</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="marcas">
        <div class="row">
            <div class="col-md-12 center-block">
                <div class="title-block title-margin">
                    <div class="row justify-content-between">
                        <div class="col-md-6">
                            <h1 class="title">Lista de Marcas</h1>
                            <p class="title-description">y modelos respectivos</p>
                        </div>
                        <div class="col-md-6">
                            <button type="button" id="open_form_marcas" class="btn btn-success pull-right" data-toggle="modal" data-target="#add-marca-modal" title="Agregar Nueva Marca">
                                <i class="fa fa-plus"></i>
                                Agregar Nueva Marca
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 center-block">
                <div class="card">
                    <div class="card-block">
                        <p id="output-success-marca"></p>
                        <table class="table table-bordered table-hover" id="marcas-table" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Marca</th>
                                    <th>Modelos</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script> 
        var route = {
            //ruta productos
            'get_productos': '{{ route('get_data_productos') }}',
            'download_pdf': '{{ route('get_link_pdf') }}',
            'del_producto': '{{ route('del_data_producto') }}',
            //rutas categorias
            'get_categorias': '{{ route('get_data_categorias') }}',
            'set_categoria': '{{ route('set_data_categoria') }}',
            'upd_categoria': '{{ route('upd_data_categoria') }}',
            'del_categoria': '{{ route('del_data_categoria') }}',
            //rutas marcas
            'get_marcas': '{{ route('get_data_marcas') }}',
            'set_marca': '{{ route('set_data_marca') }}',
            'upd_marca': '{{ route('upd_data_marca') }}',
            'del_marca': '{{ route('del_data_marca') }}',
        };
    </script>
    <script type="text/javascript" src="{{asset('plugins/DataTables/datatables.min.js')}}"></script>
    <script src="{{asset ('js/modal.js')}}"></script>
    <script src="{{asset ('js/tables.js')}}"></script>
    <script src="{{asset ('js/Productos/jquery.custom-file-input.js')}}"></script>
@endsection

@include('admin.modals')

resources/views/admin/principal2.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h1>Acá va algún menu</h1>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection