routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontPageController@index')->name('welcome');

Route::get('/admin/instructivo', function () {
    return view('admin.instructivo');
});

Route::get('/categoria/{id}', 'FrontPageController@showCategoria')->name('categoria');

Auth::routes();

//Route::get('/admin', 'PrincipalController@index');
Route::get('/admin', ['as' => 'admin', 'uses' => 'PrincipalController@index']);
Route::get('/admin/productos/get_data_productos', ['as' => 'get_data_productos', 'uses' => 'ProductosController@get_data']);
Route::get('/admin/productos/get_link_pdf', ['as' => 'get_link_pdf', 'uses' => 'ProductosController@download_pdf']);
Route::get('/admin/categorias/get_data_categorias', ['as' => 'get_data_categorias', 'uses' => 'CategoriasController@get_data']);
Route::get('/admin/marcas/get_data_marcas', ['as' => 'get_data_marcas', 'uses' =>'MarcasController@get_data']);
//CATEGORIAS
Route::get('/admin/productos/get_tipos/{id}', 'CategoriasController@getTipos')->name('get_tipos_selectbox');
Route::post('/admin/categorias/set_data_categoria', 'CategoriasController@store')->name('set_data_categoria');
Route::patch('/admin/categorias/upd_data_categoria', 'CategoriasController@update')->name('upd_data_categoria');
Route::delete('/admin/categorias/del_data_categoria', 'CategoriasController@destroy')->name('del_data_categoria');
//MARCAS
Route::get('/admin/productos/get_modelos/{id}', 'MarcasController@getModelos')->name('get_modelos_selectbox');
Route::post('/admin/marcas/set_data_marca', 'MarcasController@store')->name('set_data_marca');
Route::patch('/admin/marcas/upd_data_marca', 'MarcasController@update')->name('upd_data_marca');
Route::delete('/admin/marcas/del_data_marca', 'MarcasController@destroy')->name('del_data_marca');
//PRODUCTOS
Route::resource('/admin/productos', 'ProductosController');
Route::post('/admin/productos/set_data_producto', 'ProductosController@store')->name('set_data_producto');
Route::delete('/admin/productos/del_data_producto', 'ProductosController@destroy')->name('del_data_producto');
/* Route::resource('/admin/categorias', 'CategoriasController'); */
/* Route::resource('/admin/marcas', 'MarcasController'); */

resources/views/layouts/admin.blade.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name') }} - Administración</title>
        <link rel="shortcut icon" href="{{asset('img/logos/favicon.ico')}}">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{{ asset('css/bootstrap-grid.css') }}" rel="stylesheet">
        <link href="{{ asset('css/vendor.css') }}" rel="stylesheet">
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('css/mod-admin.css') }}" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css">
        @yield('styles')
    </head>
    <body>
        <div class="main-wrapper">
            <div class="app" id="app">
                <header class="header">
                    <div class="header-block header-block-collapse hidden-lg-up"> <button class="collapse-btn" id="sidebar-collapse-btn">
                        <i class="fa fa-bars"></i>
                        </button> 
                    </div>
                    <div class="header-block header-block-nav">
                        <ul class="nav-profile">
                            <li class="notifications new sidebar-li"></li>
                            <li class="profile dropdown sidebar-li">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="name">
                                    {{ Auth::user()->name }}
                                    </span> 
                                </a>
                                <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <a class="dropdown-item" href="#">
                                        <i class="fa fa-user icon"></i>
                                        Perfil
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="fa fa-power-off icon"></i>
                                        Salir
                                    </a> 
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </div>
                </header>
                <aside class="sidebar">
                    <div class="sidebar-container">
                        <div class="sidebar-header">
                            <div class="brand">
                                <div class="logo"> <img class="logo-sidebar" src="{{asset('img/logos/convertec_icon.png')}}"> </div>
                                {{ config('app.name') }}
                            </div>
                        </div>
                        <nav class="menu">
                            <ul class="nav metismenu" id="sidebar-menu">
                                <li class="active sidebar-li"> <a href="{{ route('login') }}">
                                    <i class="fa fa-home"></i> Principal
                                    </a> 
                                </li>
                                <li class="sidebar-li">
                                    <a href="{{ route('productos.create') }}">
                                    <i class="fa fa-microchip"></i> Agregar Productos
                                    </a>
                                </li>
                                <li class="sidebar-li">
                                    <a href="{{ url('admin/instructivo') }}" class="margin-left">
                                    <i class="fa fa-info padding-right"></i> Instrucciones
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </aside>
                    <div class="sidebar-overlay" id="sidebar-overlay"></div>
                    <article class="content responsive-tables-page" id="contenido">
                        {{-- Mensajes desde server [NO AJAX]--}}
                        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                            @if(Session::has('alert-' . $msg))
                                <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }}</p>
                            @endif
                        @endforeach

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close" title="Cerrar">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="alert-heading"><span class="fa fa-warning"></span>Se detectaron errores en:</h4>
                                <hr>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                                <hr>
                                <h5 class="alert-footer">Reingrese con datos validos.</h5>
                            </div>
                        @endif
                        {{--  --}}
                        @yield('content')
                    </article>
                <footer class="footer footer-static">
                    <div class="footer-block author">
                        <ul>
                            <li>Copyright © 2018 & Convertec, Derechos Reservados</li>
                        </ul>
                    </div>
                    <div class="footer-block author">
                        <ul>
                            <li> Plantilla creada por <a href="https://github.com/modularcode">ModularCode</a> </li>
                        </ul>
                    </div>
                </footer>
                @yield('modals')
            </div>
        </div>
        <!-- Reference block for JS -->
        <script src="{{asset ('js/jquery-3.3.1.min.js')}}"></script>
        <script src="{{asset ('js/vendor.js')}}"></script>
        <script src="{{asset ('js/app.js')}}"></script>
        @yield('scripts')
    </body>
</html>

resources/views/layouts/front.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{{ config('app.name') }}</title>
        <link rel="shortcut icon" href="{{asset('img/logos/favicon.ico')}}" />

        <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
        <link href="{{asset('css/mod.css')}}" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
        @yield('styles')
    </head>
    <body>
        @yield('nav')
        @yield('header')
        @yield('content')
        <!-- Footer -->
        @yield('footer')
    </body>
    {{-- Scripts --}}
    <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    @yield('scripts')
</html>